from django.core.management.base import BaseCommand
from core.models import NutritionalValue, Ingredient


class Command(BaseCommand):
    help = 'Populates the database with ingredients and products'

    def handle(self, *args, **options):
        ingredients = [
            {
                'name': 'F. Chicken fillet (boiled)',
                'description': 'Boiled chicken fillet',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'protein',
                'purchase_price': 83,
                'nutritional_value': {
                    'calories': 165,
                    'proteins': 31,
                    'fats': 3.6,
                    'carbohydrates': 0,
                    'saturated_fats': 1,
                    'sugars': 0,
                    'fiber': 0,

                    'vitamin_a': 13,  # IU
                    'vitamin_c': 0,  # mg
                    'vitamin_d': 0.1,  # mcg
                    'vitamin_e': 0.3,  # mg
                    'vitamin_k': 0.3,  # mcg
                    'thiamin': 0.07,  # mg
                    'riboflavin': 0.1,  # mg
                    'niacin': 13.7,  # mg
                    'vitamin_b6': 0.6,  # mg
                    'folate': 4,  # mcg
                    'vitamin_b12': 0.3,  # mcg

                    'calcium': 11,  # mg
                    'iron': 0.9,  # mg
                    'magnesium': 29,  # mg
                    'phosphorus': 213,  # mg
                    'potassium': 256,  # mg
                    'sodium': 74,  # mg
                    'zinc': 1,  # mg
                    'copper': 0.04,  # mg
                    'manganese': 0.02,  # mg
                    'selenium': 27.6,  # mcg
                }
            },
            {
                'name': 'F. Lentils Brown (boiled)',
                'description': 'Boiled brown lentils',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'base',
                'purchase_price': 32,
                'nutritional_value': {
                    'calories': 116,
                    'proteins': 9.02,
                    'fats': 0.38,
                    'carbohydrates': 20.13,
                    'saturated_fats': 0.053,
                    'sugars': 1.8,
                    'fiber': 7.9,
                    'vitamin_a': 8,
                    'vitamin_c': 1.5,
                    'vitamin_d': 0,
                    'vitamin_e': 0.11,
                    'vitamin_k': 2.1,
                    'thiamin': 0.169,
                    'riboflavin': 0.073,
                    'niacin': 1.06,
                    'vitamin_b6': 0.178,
                    'folate': 181,
                    'vitamin_b12': 0,

                    'calcium': 19,
                    'iron': 3.33,
                    'magnesium': 36,
                    'phosphorus': 180,
                    'potassium': 369,
                    'sodium': 2,
                    'zinc': 1.27,
                    'copper': 0.251,
                    'manganese': 0.494,
                    'selenium': 2.8,
                }
            },
            {
                'name': 'F. Quinoa (boiled)',
                'description': 'Boiled quinoa',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'base',
                'purchase_price': 40,
                'nutritional_value': {
                    'calories': 120,
                    'proteins': 4.4,
                    'fats': 1.92,
                    'carbohydrates': 21.3,
                    'saturated_fats': 0.231,
                    'sugars': 0.87,
                    'fiber': 2.8,

                    'vitamin_a': 5,
                    'vitamin_c': 0,
                    'vitamin_d': 0,
                    'vitamin_e': 0.63,
                    'vitamin_k': 0,
                    'thiamin': 0.107,
                    'riboflavin': 0.110,
                    'niacin': 0.412,
                    'vitamin_b6': 0.123,
                    'folate': 42,
                    'vitamin_b12': 0,

                    'calcium': 17,
                    'iron': 1.49,
                    'magnesium': 64,
                    'phosphorus': 152,
                    'potassium': 172,
                    'sodium': 7,
                    'zinc': 1.09,
                    'copper': 0.191,
                    'manganese': 0.631,
                    'selenium': 2.8,
                }
            },
            {
                'name': 'F. Salmon (boiled)',
                'description': 'Boiled salmon',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'protein',
                'purchase_price': 280,
                'nutritional_value': {
                    'calories': 208,
                    'proteins': 22.1,
                    'fats': 13.4,
                    'carbohydrates': 0,
                    'saturated_fats': 3.1,
                    'sugars': 0,
                    'fiber': 0,

                    'vitamin_a': 149,
                    'vitamin_c': 0,
                    'vitamin_d': 13.1,
                    'vitamin_e': 3.55,
                    'vitamin_k': 0.3,
                    'thiamin': 0.23,
                    'riboflavin': 0.38,
                    'niacin': 8.5,
                    'vitamin_b6': 0.98,
                    'folate': 25,
                    'vitamin_b12': 2.38,

                    'calcium': 9,
                    'iron': 0.3,
                    'magnesium': 27,
                    'phosphorus': 200,
                    'potassium': 363,
                    'sodium': 59,
                    'zinc': 0.64,
                    'copper': 0.05,
                    'manganese': 0.02,
                    'selenium': 36.5,
                }
            },
            {
                'name': 'F. Olive Oil',
                'description': 'Extra virgin olive oil',
                'min_order': 5,
                'max_order': 50,
                'step': 1,
                'ingredient_type': 'other',
                'purchase_price': 300,
                'nutritional_value': {
                    'calories': 884,
                    'proteins': 0,
                    'fats': 100,
                    'carbohydrates': 0,
                    'saturated_fats': 13.8,
                    'sugars': 0,
                    'fiber': 0,

                    'vitamin_a': 0,
                    'vitamin_c': 0,
                    'vitamin_d': 0,
                    'vitamin_e': 14.35,
                    'vitamin_k': 60.2,
                    'thiamin': 0,
                    'riboflavin': 0,
                    'niacin': 0,
                    'vitamin_b6': 0,
                    'folate': 0,
                    'vitamin_b12': 0,

                    'calcium': 1,
                    'iron': 0.56,
                    'magnesium': 0,
                    'phosphorus': 0,
                    'potassium': 1,
                    'sodium': 2,
                    'zinc': 0,
                    'copper': 0,
                    'manganese': 0,
                    'selenium': 0,
                }
            },
            {
                'name': 'F. Avocado (Indonesia)',
                'description': 'Fresh Indonesian avocado',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 30,
                'nutritional_value': {
                    'calories': 160,
                    'proteins': 2,
                    'fats': 14.7,
                    'carbohydrates': 8.5,
                    'saturated_fats': 2.1,
                    'sugars': 0.7,
                    'fiber': 6.7,

                    'vitamin_a': 146,
                    'vitamin_c': 10,
                    'vitamin_d': 0,
                    'vitamin_e': 2.07,
                    'vitamin_k': 21,
                    'thiamin': 0.067,
                    'riboflavin': 0.13,
                    'niacin': 1.738,
                    'vitamin_b6': 0.257,
                    'folate': 81,
                    'vitamin_b12': 0,

                    'calcium': 12,
                    'iron': 0.55,
                    'magnesium': 29,
                    'phosphorus': 52,
                    'potassium': 485,
                    'sodium': 7,
                    'zinc': 0.64,
                    'copper': 0.15,
                    'manganese': 0.142,
                    'selenium': 0.4,
                }
            },
            {
                'name': 'F. Flaxseed',
                'description': 'Raw flaxseed',
                'min_order': 1,
                'max_order': 50,
                'step': 1,
                'ingredient_type': 'topping',
                'purchase_price': 15,
                'nutritional_value': {
                    'calories': 534,
                    'proteins': 18.3,
                    'fats': 42.2,
                    'carbohydrates': 28.9,
                    'saturated_fats': 3.7,
                    'sugars': 1.5,
                    'fiber': 27.3,

                    'vitamin_a': 0,
                    'vitamin_c': 0.6,
                    'vitamin_d': 0,
                    'vitamin_e': 0.31,
                    'vitamin_k': 4.3,
                    'thiamin': 1.644,
                    'riboflavin': 0.161,
                    'niacin': 3.08,
                    'vitamin_b6': 0.473,
                    'folate': 87,
                    'vitamin_b12': 0,

                    'calcium': 255,
                    'iron': 5.73,
                    'magnesium': 392,
                    'phosphorus': 642,
                    'potassium': 813,
                    'sodium': 30,
                    'zinc': 4.34,
                    'copper': 1.22,
                    'manganese': 2.482,
                    'selenium': 25.4,
                }
            },
            {
                'name': 'F. Eggs',
                'description': 'Whole eggs',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'protein',
                'purchase_price': 40,
                'nutritional_value': {
                    'calories': 155,
                    'proteins': 12.6,
                    'fats': 10.6,
                    'carbohydrates': 1.1,
                    'saturated_fats': 3.3,
                    'sugars': 1.1,
                    'fiber': 0,

                    'vitamin_a': 540,
                    'vitamin_c': 0,
                    'vitamin_d': 2,
                    'vitamin_e': 1.05,
                    'vitamin_k': 0.3,
                    'thiamin': 0.04,
                    'riboflavin': 0.457,
                    'niacin': 0.075,
                    'vitamin_b6': 0.17,
                    'folate': 47,
                    'vitamin_b12': 0.89,

                    'calcium': 56,
                    'iron': 1.75,
                    'magnesium': 12,
                    'phosphorus': 198,
                    'potassium': 138,
                    'sodium': 142,
                    'zinc': 1.29,
                    'copper': 0.072,
                    'manganese': 0.028,
                    'selenium': 30.7,
                }
            },
            {
                'name': 'F. Broccoli',
                'description': 'Fresh broccoli',
                'min_order': 25,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 60,
                'nutritional_value': {
                    'calories': 34,
                    'proteins': 2.8,
                    'fats': 0.4,
                    'carbohydrates': 6.6,
                    'saturated_fats': 0.1,
                    'sugars': 1.7,
                    'fiber': 2.6,

                    'vitamin_a': 623,
                    'vitamin_c': 89.2,
                    'vitamin_d': 0,
                    'vitamin_e': 0.78,
                    'vitamin_k': 101.6,
                    'thiamin': 0.071,
                    'riboflavin': 0.117,
                    'niacin': 0.639,
                    'vitamin_b6': 0.175,
                    'folate': 63,
                    'vitamin_b12': 0,

                    'calcium': 47,
                    'iron': 0.73,
                    'magnesium': 21,
                    'phosphorus': 66,
                    'potassium': 316,
                    'sodium': 33,
                    'zinc': 0.41,
                    'copper': 0.049,
                    'manganese': 0.21,
                    'selenium': 2.5,
                }
            },
            {
                'name': 'F. Tomato Usual',
                'description': 'Fresh regular tomato',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 30,
                'nutritional_value': {
                    'calories': 18,
                    'proteins': 0.9,
                    'fats': 0.2,
                    'carbohydrates': 3.9,
                    'saturated_fats': 0,
                    'sugars': 2.6,
                    'fiber': 1.2,

                    'vitamin_a': 833,
                    'vitamin_c': 13.7,
                    'vitamin_d': 0,
                    'vitamin_e': 0.54,
                    'vitamin_k': 7.9,
                    'thiamin': 0.037,
                    'riboflavin': 0.019,
                    'niacin': 0.594,
                    'vitamin_b6': 0.08,
                    'folate': 15,
                    'vitamin_b12': 0,

                    'calcium': 10,
                    'iron': 0.27,
                    'magnesium': 11,
                    'phosphorus': 24,
                    'potassium': 237,
                    'sodium': 5,
                    'zinc': 0.17,
                    'copper': 0.059,
                    'manganese': 0.114,
                    'selenium': 0,
                }
            },
            {
                'name': 'F. Tomato Cherry',
                'description': 'Fresh cherry tomatoes',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 25,
                'nutritional_value': {
                    'calories': 27,
                    'proteins': 1.3,
                    'fats': 0.3,
                    'carbohydrates': 5.8,
                    'saturated_fats': 0,
                    'sugars': 4.0,
                    'fiber': 1.8,

                    'vitamin_a': 1000,
                    'vitamin_c': 20.4,
                    'vitamin_d': 0,
                    'vitamin_e': 0.89,
                    'vitamin_k': 10.1,
                    'thiamin': 0.048,
                    'riboflavin': 0.028,
                    'niacin': 0.739,
                    'vitamin_b6': 0.139,
                    'folate': 19,
                    'vitamin_b12': 0,

                    'calcium': 15,
                    'iron': 0.31,
                    'magnesium': 14,
                    'phosphorus': 33,
                    'potassium': 290,
                    'sodium': 7,
                    'zinc': 0.19,
                    'copper': 0.083,
                    'manganese': 0.133,
                    'selenium': 0,
                }
            },
            {
                'name': 'F. Shiitake Mushroom',
                'description': 'Fresh shiitake mushrooms',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 65,
                'nutritional_value': {
                    'calories': 34,
                    'proteins': 2.2,
                    'fats': 0.5,
                    'carbohydrates': 6.8,
                    'saturated_fats': 0.1,
                    'sugars': 2.4,
                    'fiber': 2.5,

                    'vitamin_a': 0,
                    'vitamin_c': 0,
                    'vitamin_d': 0.4,
                    'vitamin_e': 0.01,
                    'vitamin_k': 2.6,
                    'thiamin': 0.015,
                    'riboflavin': 0.217,
                    'niacin': 3.877,
                    'vitamin_b6': 0.293,
                    'folate': 13,
                    'vitamin_b12': 0,

                    'calcium': 2,
                    'iron': 0.41,
                    'magnesium': 20,
                    'phosphorus': 112,
                    'potassium': 304,
                    'sodium': 9,
                    'zinc': 1.03,
                    'copper': 0.142,
                    'manganese': 0.229,
                    'selenium': 5.7,
                }
            },
            {
                'name': 'F. Walnuts',
                'description': 'Raw walnuts',
                'min_order': 5,
                'max_order': 50,
                'step': 1,
                'ingredient_type': 'topping',
                'purchase_price': 200,
                'nutritional_value': {
                    'calories': 654,
                    'proteins': 15.2,
                    'fats': 65.2,
                    'carbohydrates': 13.7,
                    'saturated_fats': 6.1,
                    'sugars': 2.6,
                    'fiber': 6.7,

                    'vitamin_a': 20,
                    'vitamin_c': 1.3,
                    'vitamin_d': 0,
                    'vitamin_e': 0.7,
                    'vitamin_k': 2.7,
                    'thiamin': 0.341,
                    'riboflavin': 0.15,
                    'niacin': 1.125,
                    'vitamin_b6': 0.537,
                    'folate': 98,
                    'vitamin_b12': 0,

                    'calcium': 98,
                    'iron': 2.91,
                    'magnesium': 158,
                    'phosphorus': 346,
                    'potassium': 441,
                    'sodium': 2,
                    'zinc': 3.09,
                    'copper': 1.586,
                    'manganese': 3.414,
                    'selenium': 4.9,
                }
            },
            {
                'name': 'F. Tofu',
                'description': 'Regular tofu',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'protein',
                'purchase_price': 30,
                'nutritional_value': {
                    'calories': 76,
                    'proteins': 8,
                    'fats': 4.8,
                    'carbohydrates': 1.9,
                    'saturated_fats': 0.7,
                    'sugars': 0.7,
                    'fiber': 0.3,

                    'vitamin_a': 85,
                    'vitamin_c': 0.1,
                    'vitamin_d': 0,
                    'vitamin_e': 0.01,
                    'vitamin_k': 2.6,
                    'thiamin': 0.08,
                    'riboflavin': 0.052,
                    'niacin': 0.2,
                    'vitamin_b6': 0.047,
                    'folate': 15,
                    'vitamin_b12': 0,

                    'calcium': 350,
                    'iron': 2.66,
                    'magnesium': 37,
                    'phosphorus': 121,
                    'potassium': 121,
                    'sodium': 7,
                    'zinc': 1,
                    'copper': 0.362,
                    'manganese': 0.861,
                    'selenium': 17.4,
                }
            },
            {
                'name': 'F. Spinach',
                'description': 'Fresh spinach',
                'min_order': 5,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 35,
                'nutritional_value': {
                    'calories': 23,
                    'proteins': 2.9,
                    'fats': 0.4,
                    'carbohydrates': 3.6,
                    'saturated_fats': 0.1,
                    'sugars': 0.4,
                    'fiber': 2.2,

                    'vitamin_a': 9377,
                    'vitamin_c': 28.1,
                    'vitamin_d': 0,
                    'vitamin_e': 2.03,
                    'vitamin_k': 483,
                    'thiamin': 0.078,
                    'riboflavin': 0.189,
                    'niacin': 0.724,
                    'vitamin_b6': 0.195,
                    'folate': 194,
                    'vitamin_b12': 0,

                    'calcium': 99,
                    'iron': 2.71,
                    'magnesium': 79,
                    'phosphorus': 49,
                    'potassium': 558,
                    'sodium': 79,
                    'zinc': 0.53,
                    'copper': 0.13,
                    'manganese': 0.897,
                    'selenium': 1,
                }
            },
            {
                'name': 'F. Red Cabbage',
                'description': 'Fresh red cabbage',
                'min_order': 5,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 30,
                'nutritional_value': {
                    'calories': 31,
                    'proteins': 1.4,
                    'fats': 0.2,
                    'carbohydrates': 7.4,
                    'saturated_fats': 0,
                    'sugars': 3.8,
                    'fiber': 2.1,

                    'vitamin_a': 1116,
                    'vitamin_c': 57,
                    'vitamin_d': 0,
                    'vitamin_e': 0.11,
                    'vitamin_k': 38.2,
                    'thiamin': 0.06,
                    'riboflavin': 0.069,
                    'niacin': 0.418,
                    'vitamin_b6': 0.209,
                    'folate': 18,
                    'vitamin_b12': 0,

                    'calcium': 45,
                    'iron': 0.8,
                    'magnesium': 16,
                    'phosphorus': 30,
                    'potassium': 243,
                    'sodium': 27,
                    'zinc': 0.22,
                    'copper': 0.017,
                    'manganese': 0.216,
                    'selenium': 0.6,
                }
            },
            {
                'name': 'F. Parsley',
                'description': 'Fresh parsley',
                'min_order': 5,
                'max_order': 50,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 35,
                'nutritional_value': {
                    'calories': 36,
                    'proteins': 3,
                    'fats': 0.8,
                    'carbohydrates': 6.3,
                    'saturated_fats': 0.1,
                    'sugars': 0.9,
                    'fiber': 3.3,

                    'vitamin_a': 8424,
                    'vitamin_c': 133,
                    'vitamin_d': 0,
                    'vitamin_e': 0.75,
                    'vitamin_k': 1640,
                    'thiamin': 0.086,
                    'riboflavin': 0.098,
                    'niacin': 1.313,
                    'vitamin_b6': 0.09,
                    'folate': 152,
                    'vitamin_b12': 0,

                    'calcium': 138,
                    'iron': 6.2,
                    'magnesium': 50,
                    'phosphorus': 58,
                    'potassium': 554,
                    'sodium': 56,
                    'zinc': 1.07,
                    'copper': 0.149,
                    'manganese': 0.16,
                    'selenium': 0.1,
                }
            },
            {
                'name': 'F. Arugula',
                'description': 'Fresh arugula (ruccola)',
                'min_order': 5,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'vegetable',
                'purchase_price': 35,
                'nutritional_value': {
                    'calories': 25,
                    'proteins': 2.6,
                    'fats': 0.7,
                    'carbohydrates': 3.7,
                    'saturated_fats': 0.1,
                    'sugars': 2.1,
                    'fiber': 1.6,

                    'vitamin_a': 2373,
                    'vitamin_c': 15,
                    'vitamin_d': 0,
                    'vitamin_e': 0.43,
                    'vitamin_k': 109,
                    'thiamin': 0.044,
                    'riboflavin': 0.086,
                    'niacin': 0.305,
                    'vitamin_b6': 0.073,
                    'folate': 97,
                    'vitamin_b12': 0,

                    'calcium': 160,
                    'iron': 1.46,
                    'magnesium': 47,
                    'phosphorus': 52,
                    'potassium': 369,
                    'sodium': 27,
                    'zinc': 0.47,
                    'copper': 0.076,
                    'manganese': 0.321,
                    'selenium': 0.3,
                }
            },
            {
                'name': 'F. Violet Sweet Potato',
                'description': 'Fresh violet sweet potato',
                'min_order': 10,
                'max_order': 200,
                'step': 5,
                'ingredient_type': 'base',
                'purchase_price': 12,
                'nutritional_value': {
                    'calories': 86,
                    'proteins': 1.6,
                    'fats': 0.1,
                    'carbohydrates': 20.1,
                    'saturated_fats': 0,
                    'sugars': 4.2,
                    'fiber': 3,

                    'vitamin_a': 14187,
                    'vitamin_c': 2.4,
                    'vitamin_d': 0,
                    'vitamin_e': 0.26,
                    'vitamin_k': 2.3,
                    'thiamin': 0.078,
                    'riboflavin': 0.061,
                    'niacin': 0.557,
                    'vitamin_b6': 0.209,
                    'folate': 11,
                    'vitamin_b12': 0,

                    'calcium': 30,
                    'iron': 0.61,
                    'magnesium': 25,
                    'phosphorus': 47,
                    'potassium': 337,
                    'sodium': 55,
                    'zinc': 0.3,
                    'copper': 0.151,
                    'manganese': 0.258,
                    'selenium': 0.6,
                }
            }
        ]

        # Create ingredients in the database
        created_ingredients = []
        for ingredient_data in ingredients:
            nutritional_value_data = ingredient_data.pop('nutritional_value')
            nutritional_value = NutritionalValue.objects.create(**nutritional_value_data)
            ingredient = Ingredient.objects.create(nutritional_value=nutritional_value, **ingredient_data)
            created_ingredients.append(ingredient)

        print("Ingredients successfully created!")
