# Generated by Django 5.1.2 on 2024-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
