# Generated by Django 5.1.2 on 2024-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderproduct_order_alter_product_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
    ]
