# Generated by Django 5.1.2 on 2024-10-21 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('base', 'Base'), ('protein', 'Protein'), ('vegetable', 'Vegetable'), ('dairy', 'Dairy'), ('fruit', 'Fruit'), ('topping', 'Topping'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(upload_to='ingredients/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='max_order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='min_order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
