# Generated by Django 5.1.2 on 2024-10-21 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_is_refunded_order_paid_at_order_ready_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='weight_grams',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
