# Generated by Django 5.1.2 on 2024-10-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productingredient_weight_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='step',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
