# Generated by Django 5.1.2 on 2024-10-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_ingredient_private_note_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='user',
        ),
    ]
