# Generated by Django 5.1.2 on 2024-10-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_table_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quantity',
            new_name='amount',
        ),
    ]
