# Generated by Django 5.1.2 on 2024-10-22 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_quantity_orderproduct_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nutritional_value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.nutritionalvalue'),
        ),
    ]
