# Generated by Django 5.1.2 on 2024-10-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_nutritional_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nutritional_value',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.nutritionalvalue'),
        ),
    ]
