# Generated by Django 5.1.2 on 2024-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_nutritional_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('qr', 'QR')], default='card', max_length=20),
        ),
    ]
