# Generated by Django 5.1.2 on 2024-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='private_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='public_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
