# Generated by Django 5.1.2 on 2024-10-22 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_private_note_order_public_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='raw_price',
            new_name='price_no_tax',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fee',
            new_name='tax',
        ),
        migrations.AlterField(
            model_name='order',
            name='public_note',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
