# Generated by Django 5.1.2 on 2024-10-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_raw_price_order_price_no_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_official',
            new_name='is_menu',
        ),
    ]
