# Generated by Django 5.1.2 on 2024-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_is_official_product_is_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
