# Generated by Django 5.1.2 on 2024-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_is_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_official',
            field=models.BooleanField(),
        ),
    ]
