# Generated by Django 5.1.2 on 2024-10-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_product_is_official'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_no_tax',
            new_name='base_price',
        ),
    ]
